### ISSUE TITLE
As a signed-in user, I want to edit my profile, so that I can change/ update my username, name, bio, and profile picture

### ISSUE THREAD

**Issue by amn493** [agile-dev-assignments/project-setup-team-ntobo-global#26]
**Acceptance Criteria**
~1. Capture new username~
~2. Capture new first name~
~3. Capture new last name~
~4. Capture new bio~
~5. Capture new profile picture~
6. Display appropriate error message (and do not update) if user enters invalid information
7. Disable `Save Changes` button if username field is empty

**Estimation of Work**
8

**Comment by Dendrobyte** [comment]
7 completed in Sprint 2, but 6 incomplete as we need to make a get request that finds out if some `username` is taken by checking if a user exists where `username` equals what an app user attempted to change their username too.
