### ISSUE TITLE
Deploying to Digital Ocean Droplet

### ISSUE THREAD

**Issue by JonathanSussman1** [agile-dev-assignments/project-setup-team-ntobo-global#453]
Each project must deploy their application front-and-back-ends to a single Digital Ocean Droplet - sign up for Digital Ocean using [this referral link](https://m.do.co/c/4d1066078eb0) to receive $100 of credit

**Comment by Dendrobyte** [comment]
Keep [this in mind](https://stackabuse.com/deploying-a-node-js-app-to-a-digitalocean-droplet-with-docker/) for deploying a Docker container. Set up Digital Ocean first and Docker task will be done "separately".

Send relevant details to the person who is doing that task for the Digital Ocean account.

**Comment by Dendrobyte** [comment]
Currently in progress. Need to work with nginx so the routing works, almost done.
